const selectedItem = this.getSelectedItem();

if (selectedItem) {
    const context = selectedItem.getBindingContext();
    const data = context.getObject();

    const options = {
        parameters: {
            fileName: data.name,
            pathing: ToolTopUrlPath.getSelectedKey()
        },
    };

    apiGetRequestLog(options).then(function (res) {
        modelTabTopUrl.setData(res.topUrlList);
        modelPageAnalyze.setData(res.requestInfo);
    });
}
